### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/srophe#31]
@wsalesky I managed to merge my changes in the end. However, when I cleared my cache and opened srophé again, there was an error message. I assumed that it was my latest change – so I reverted it. But the error persists.

Please help!

```
<h2>HTTP ERROR 500 javax.servlet.ServletException: 
javax.servlet.ServletException: An error occurred while processing 
request to /exist/apps/majlis/: err:XPST0003 error found while loading 
module config: Error while loading module modules/config.xqm: error 
found while loading module from modules/config.xqm: 
org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' 
[at line 1, column 4]
</h2>


URI: | /exist/apps/majlis/
-- | --
500
javax.servlet.ServletException:  javax.servlet.ServletException: An error occurred while processing  request to /exist/apps/majlis/: err:XPST0003 error found while loading  module config: Error while loading module modules/config.xqm: error  found while loading module from modules/config.xqm:  org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':'  [at line 1, column 4]
XQueryURLRewrite
javax.servlet.ServletException:  javax.servlet.ServletException: An error occurred while processing  request to /exist/apps/majlis/: err:XPST0003 error found while loading  module config: Error while loading module modules/config.xqm: error  found while loading module from modules/config.xqm:  org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':'  [at line 1, column 4]
javax.servlet.ServletException: An error  occurred while processing request to /exist/apps/majlis/: err:XPST0003  error found while loading module config: Error while loading module  modules/config.xqm: error found while loading module from  modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003  expecting EOF, found ':' [at line 1, column 4]
org.exist.xquery.XPathException: err:XPST0003  error found while loading module config: Error while loading module  modules/config.xqm: error found while loading module from  modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003  expecting EOF, found ':' [at line 1, column 4]


<h3>Caused by:</h3><pre>javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]

	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:366)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 18 more
Caused by: org.exist.xquery.XPathException: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]

	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2652)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2599)
	at org.exist.xquery.XQueryContext.importModuleFromLocation(XQueryContext.java:2528)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2462)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6276)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5291)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:3991)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3936)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3591)
	at org.exist.xquery.XQuery.compile(XQuery.java:238)
	at org.exist.xquery.XQuery.compile(XQuery.java:175)
	at org.exist.xquery.XQuery.compile(XQuery.java:133)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:239)
	... 41 more
</pre>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.44.v20210927</a><hr>



<div id="merlinExt-merlinGUI" class="merlinExt merlinGUI"></div><div id="merlinExt-ctrlGMessage" class="merlinExt ctrlGMessage"></div><div id="merlinExt-selectContextBtn" class="merlinExt selectContextBtn"></div>HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]
URI:	/exist/apps/majlis/
STATUS:	500
MESSAGE:	javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]
SERVLET:	XQueryURLRewrite
CAUSED BY:	javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]
CAUSED BY:	javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]
CAUSED BY:	org.exist.xquery.XPathException: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]
Caused by:

javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.lang.Thread.run(Thread.java:750)
Caused by: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/majlis/: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]

	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:366)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 18 more
Caused by: org.exist.xquery.XPathException: err:XPST0003 error found while loading module config: Error while loading module modules/config.xqm: error found while loading module from modules/config.xqm: org.exist.xquery.XPathException: err:XPST0003 expecting EOF, found ':' [at line 1, column 4]

	at org.exist.xquery.XQueryContext.compileModule(XQueryContext.java:2652)
	at org.exist.xquery.XQueryContext.compileOrBorrowModule(XQueryContext.java:2599)
	at org.exist.xquery.XQueryContext.importModuleFromLocation(XQueryContext.java:2528)
	at org.exist.xquery.XQueryContext.importModule(XQueryContext.java:2462)
	at org.exist.xquery.parser.XQueryTreeParser.importDecl(XQueryTreeParser.java:6276)
	at org.exist.xquery.parser.XQueryTreeParser.prolog(XQueryTreeParser.java:5291)
	at org.exist.xquery.parser.XQueryTreeParser.mainModule(XQueryTreeParser.java:3991)
	at org.exist.xquery.parser.XQueryTreeParser.module(XQueryTreeParser.java:3936)
	at org.exist.xquery.parser.XQueryTreeParser.xpath(XQueryTreeParser.java:3591)
	at org.exist.xquery.XQuery.compile(XQuery.java:238)
	at org.exist.xquery.XQuery.compile(XQuery.java:175)
	at org.exist.xquery.XQuery.compile(XQuery.java:133)
	at org.exist.http.urlrewrite.XQueryURLRewrite.runQuery(XQueryURLRewrite.java:669)
	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:239)
	... 41 more

[Powered by Jetty:// 9.4.44.v20210927](https://eclipse.org/jetty)
```

**Comment by wsalesky** [comment]
@mMoliere Hum. This is odd. I will try to untangle it. 
For the future, the best way to make changes is to create an issue: 
1. checkout master, 
2. fetch master to make sure you have the most up to date version
3. create a new branch off of master (I usually name it after my issue# for simplicity)
4. make changes (check your changes on your local installation, if you don't have one, you should, this will prevent any unpleasant surprises with code changes)
5. commit changes to your branch
6. make a pull request
7. check that only the files you have changed are changed in the pull request (for example I see a number of changes made to the xquery files, that I'm sure you were not changing)
8. merge pull request after checking and testing changes

**Comment by wsalesky** [comment]
@mMoliere Okay, I think we are back on track. You can try a new creating your change as I suggested above. If you request my review on the pull request before you merge, I can make sure there are no obvious issues that might cause an error.

**Comment by mMoliere** [comment]
@wsalesky Thank you!
